#pragma once

#include "LAB_color_hdr.h"

#define LAB_LIGHTNESS_DARK 0u
#define LAB_LIGHTNESS_SUNLIGHT LAB_HDR_UNIT_WHITE
//#define LAB_LIGHTNESS_SUNLIGHT_MARKER 0xffffffff
#define LAB_LIGHTNESS_SUNLIGHT_MARKER LAB_HDR_UNIT_WHITE