#ifdef LAB_BUILTIN_VIS

LAB_BUILTIN_VIS
LAB_SurfaceBiomeID
    LAB_SURFACE_BIOME_FOREST,
    LAB_SURFACE_BIOME_BIRCH_FOREST,
    LAB_SURFACE_BIOME_TAIGA,
    LAB_SURFACE_BIOME_PLAINS,
    LAB_SURFACE_BIOME_DESERT,

    LAB_SURFACE_BIOME_MOUNTAIN,
    LAB_SURFACE_BIOME_SNOWY_MOUNTAIN,
    LAB_SURFACE_BIOME_MEADOW;

#endif